name: run unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3
      - name: install deps
        run: |
          sudo apt-get update && sudo apt-get install -y gnat make gprbuild wget \
          unzip git curl libaunit20-dev
          sudo wget 'https://github.com/alire-project/alire/releases/download/v1.2.2/alr-1.2.2-bin-x86_64-linux.zip' \
          -O /usr/local/alire.zip && \
          sudo unzip /usr/local/alire.zip -d /usr/local && \
          sudo rm /usr/local/alire.zip

           
          sudo /usr/local/bin/alr toolchain --select gprbuild
          echo 'PATH=$PATH:/usr/local/bin' | sudo tee -a /etc/environment
      - name: run tests
        run: |
          ls ./
          make run-unit-tests
